### ISSUE TITLE
module_geoip: when parameter is a nick, module gets the oldes entry in the database

### ISSUE THREAD

**Issue by hmmp** [lepinkainen/pyfibot#147]
When using the geoip module with a nickname parameter the module gets user's host from the usertrack database but doesn't order the results by action_time, so the host from the database is the oldest one.

```
if user_track_available:
    table = get_table(bot, channel)
    user = table.find_one(nick=args)
```
https://github.com/lepinkainen/pyfibot/blob/master/pyfibot/modules/module_geoip.py#L33

**Comment by aapa** [comment]
Yes, it doesn't matter though since there should always be only one row per user.

Compare to `command_seen` in [module_usertrack.py](https://github.com/lepinkainen/pyfibot/blob/master/pyfibot/modules/module_usertrack.py#L290):

```python
def command_seen(bot, user, channel, args):
    '''Displays the last action by the given user'''

    if not args:
        return bot.say(channel, 'Please provide a nick to search...')
    table = get_table(bot, channel)

    # Return the first match, there shouldn't be multiples anyway
    user = table.find_one(nick=args)
```

This issue can be closed.
