### ISSUE TITLE
test_wolfram_alpha: Tests fail if server does not respond

### ISSUE THREAD

**Issue by aapa** [lepinkainen/pyfibot#153]
Wolfram Alpha tests seem to fail [quite randomly](https://travis-ci.org/lepinkainen/pyfibot/builds/37526083):
```
AssertionError: ('#channel', u'42 = forty-two') != ('#channel', u'forty-two = XLII')
```
or [like this](https://travis-ci.org/lepinkainen/pyfibot/builds/37527796):
```
  File "/home/travis/build/lepinkainen/pyfibot/tests/test_wolfram_alpha.py", line 18, in test_simple
    result = module_wolfram_alpha.command_wa(bot, None, "#channel", query)[1]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
First one is quite difficult, it can be fixed (3bfe9f4) but who knows, maybe next time it's `forty-two = 0x2A`...
The second one could be "fixed" if tests just passed even if WA does not respond, or at least if response code is HTTP 5xx. Any opinions?

**Comment by kipe** [comment]
Should be taken care of with the current VCR-system.
