### ISSUE TITLE
Channel names with uppercase letters

### ISSUE THREAD

**Issue by hmmp** [lepinkainen/pyfibot#158]
If a channel was orginally created with uppercase letters (#EXAMPLE) and you put the channel name with lowercase (#example) to the config file, the bot declares on start that it has joined both of them like this:
[2014-11-22 22:39:31,694][INFO     ][bot            ]  joined 2 channel(s):  #example, #EXAMPLE

The bot works still quite okay but I got about 3-4 ping timeouts per day. Now that I put #EXAMPLE in the config file the ping timeouts have disappeared completely.

Edit: and it joins only to one channel.

**Comment by lepinkainen** [comment]
Can't be reproduced.
