### ISSUE TITLE
Redo the bot with asyncio

### ISSUE THREAD

**Issue by lepinkainen** [lepinkainen/pyfibot#195]
Implement the base structure of the bot with ~~Trollius~~ asyncio, replacing Twisted
- [ ] IRCProtocol class for connecting to servers
- [ ] BotCore that juggles the different IRCProtocol instances and launches modules
- [ ] Port modules to the new structure
- [ ] Python 3.4 -> only

**Comment by kipe** [comment]
As Trollius is now [deprecated](https://trollius.readthedocs.io/deprecated.html), use [asyncio](https://docs.python.org/3/library/asyncio.html) instead. (editing issue title and first message as well)
