### ISSUE TITLE
Tweets with embedded media need a whitespace between link and tweet

### ISSUE THREAD

**Issue by redfellow** [lepinkainen/pyfibot#229]
Test case, paste URL to IRC: https://twitter.com/nixcraft/status/923779788384243712
<bot> Title: @nixcraft (nixCraft): Working at porn hub ... lmaopic.twitter.com/bbeEvgpvsC

There should be whitespace between `lmao` and `pic`. Well, really, there should be `https://`, too.

**Comment by lepinkainen** [comment]
Fixed at some point.
