### ISSUE TITLE
Dig out Youtube links from crappy sites and print the direct URL

### ISSUE THREAD

**Issue by lepinkainen** [lepinkainen/pyfibot#44]
_Original author: riku.lin...@gmail.com (October 21, 2011 07:18:55)_

Example link:

http://www.iltasanomat.fi/viihde/herkkaa-pienen-elefantin-hurmaavat-ensiaskeleet/art-1288422316882.html

1) figure out where the article is on the page
2) see if there is an embedded youtube clip
3) parse youtube link
4) say on channel

Optional step 3b also parse youtube data via api, paste it with the direct youtu.be url.

_Original issue: http://code.google.com/p/pyfibot/issues/detail?id=45_

**Comment by kipe** [comment]
This would require fetching of BS every time we come across an url, is it something we really want to do?
The parsing itself shouldn't require too much work, especially if we only target `<iframe>`.

The main issue is not to print the direct url for links already targeting youtube itself...
