### ISSUE TITLE
botcore.py / pong should use running average

### ISSUE THREAD

**Issue by lepinkainen** [lepinkainen/pyfibot#7]
_Original author: riku.lin...@gmail.com (August 31, 2006 12:16:42)_

function pong in botcore.py should use a running average of the last 10 or
so pings.

This way it's possible to make the bot reconnect by examining its own ping
average.

_Original issue: http://code.google.com/p/pyfibot/issues/detail?id=7_

**Comment by kipe** [comment]
As I understand by looking at the [code](https://github.com/lepinkainen/pyfibot/blob/master/pyfibot/botcore.py#L287), this is already done -> closing.
