### ISSUE TITLE
User info should be stored

### ISSUE THREAD

**Issue by lepinkainen** [lepinkainen/pyfibot#8]
_Original author: riku.lin...@gmail.com (September 28, 2006 19:53:50)_

The bot should do a WHO #channel on join and catch the resulting
RPL_WHOREPLY -&gt; RPL_ENDOFWHO

The only really important data to store is userhost + op/voice for
authorization (make commands available to ops/voice only)

The downside is that join/part/quit needs to be monitored too and update
when necessary - if the userhost is globbed (*!user@host), there's no need
to track nick changes.

_Original issue: http://code.google.com/p/pyfibot/issues/detail?id=8_

**Comment by kipe** [comment]
This is mainly done by the `module_usertrack.py` -> closing.
Furthermore implementing `/WHO` with the current system was deemed almost impossible and therefore this is also.

The current `module_usertrack.py` does track users while the bot is in the channel, which should be enough?
